/**
 * Cross-implementation test vectors.
 *
 * Each value below was computed by the kit's Python (thread_wrap.py) and must
 * match byte-for-byte, or the two sides cannot interoperate.
 */
import { describe, it, expect } from 'vitest';
import { generateSecretKey, getPublicKey, nip44 } from 'nostr-tools';
import { bytesToHex, hexToBytes } from 'nostr-tools/utils';
import {
  computeThreadBucket,
  computeHandoffBucket,
  ecdhHex,
  getWindowId,
  expiryTimestamp,
  WINDOW_SECONDS,
} from './bucketCrypto';
import { tryUnwrapMessage, wrapThreadMessage, wrapKeyHandoff } from './giftWrap';
import { ThreadKeyStore } from './threadKeyStore';

describe('cross-implementation: pure function vectors', () => {
  it('thread bucket: sha256("a"*64 + "20000")[0] == 0x05', () => {
    expect(computeThreadBucket('a'.repeat(64), 20000)).toBe('05');
  });

  it('handoff bucket: sha256("b"*64 + "handoff" + "20000")[0] == 0xbd', () => {
    expect(computeHandoffBucket('b'.repeat(64), 20000)).toBe('bd');
  });

  it('ECDH: sha256(ECDH(sk=1, G).x) matches kit', () => {
    const sk = new Uint8Array(32);
    sk[31] = 1;
    const gx = '79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798';
    expect(ecdhHex(sk, gx)).toBe(
      '132f39a98c31baaddba6525f5d43f2954472097fa15265f45130bfdb70e51def',
    );
  });

  it('handoff bucket from ECDH(sk=1, G) at window 20000 == 0xee', () => {
    const sk = new Uint8Array(32);
    sk[31] = 1;
    const gx = '79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798';
    const ecdh = ecdhHex(sk, gx);
    expect(computeHandoffBucket(ecdh, 20000)).toBe('ee');
  });

  it('window: floor(1727222400 / 86400) == 19991', () => {
    expect(getWindowId(1727222400)).toBe(19991);
  });

  it('expiry: (19991+2)*86400 == 1727395200', () => {
    expect(expiryTimestamp(19991)).toBe(1727395200);
  });
});

describe('cross-implementation: inner payload format', () => {
  it('message inner is JSON {p, a}', () => {
    const threadSk = generateSecretKey();
    const threadHex = bytesToHex(threadSk);
    const threadPk = getPublicKey(threadSk);
    const authorPk = getPublicKey(generateSecretKey());
    const now = 1727222400 + 43200;

    const wrap = wrapThreadMessage('hello world', authorPk, threadHex, now);

    // Manually decrypt to verify inner format
    const conversationKey = nip44.v2.utils.getConversationKey(threadSk, wrap.pubkey);
    const decrypted = nip44.v2.decrypt(wrap.content, conversationKey);
    const inner = JSON.parse(decrypted);
    expect(inner).toEqual({ p: 'hello world', a: authorPk });
  });

  it('handoff inner is JSON {tid, sec, g}', () => {
    const threadSk = generateSecretKey();
    const threadHex = bytesToHex(threadSk);
    const granterSk = generateSecretKey();
    const granterPk = getPublicKey(granterSk);
    const recipientSk = generateSecretKey();
    const recipientPk = getPublicKey(recipientSk);
    const now = 1727222400 + 43200;

    const wrap = wrapKeyHandoff('test-thread', threadHex, granterSk, recipientPk, now);

    // Manually decrypt: handoff is encrypted from one-time key to recipient
    const conversationKey = nip44.v2.utils.getConversationKey(recipientSk, wrap.pubkey);
    const decrypted = nip44.v2.decrypt(wrap.content, conversationKey);
    const inner = JSON.parse(decrypted);
    expect(inner).toEqual({
      tid: 'test-thread',
      sec: threadHex,
      g: granterPk,
    });
  });
});

describe('cross-implementation: kit-made wrap round-trip', () => {
  // This event was generated by the kit's Python wrap_event() with fixed keys.
  // If tryUnwrapMessage cannot open it, the TS and Python sides are incompatible.
  const KIT_FIXTURE = {
    thread_secret_hex: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    thread_pubkey_hex: '4646ae5047316b4230d0086c8acec687f00b1cd9d1dc634f6cb358ac0a9a8fff',
    author_pubkey_hex: '88e2ddeb04657dbd0edadf9c1f98da3b3895faa1f00527934dd35d17542ffe9b',
    plaintext: 'hello from the kit',
    wrap_pubkey: '6a04ab98d9e4774ad806e302dddeb63bea16b5cb5f223ee77478e861bb583eb3',
    wrap_content: 'Asly8H3tktj5OISPiixAXbFVqNGYabQSf/mnYdRGQ51jWbji76/fHNsmGqoV+lt+lL0JZiRCVtAgOprVjc81902F6ij4VSRWq/e8Tn+QbZMUOMjcFAaESgYxkRWUCfw0nXYpEqM4eS+XEzDZHEGJUpZ8pLlahGYGOwlsHqlIOk7ipZZONGySLQR7SJcDhr9B+OOkkf4qTlRpQU9gk2AUBQeRN9U1ICoA5TNnOj8ddE9f+uBwGqm7Yqb3k2+/lFq88UaZ',
    wrap_id: 'ce46b62170944884ccc4fdfc803c270704dfb8e51bee7b2f31497bf112bb961f',
  };

  it('TypeScript tryUnwrapMessage opens a kit-made wrap', () => {
    const store = new ThreadKeyStore();
    store.importHex(KIT_FIXTURE.thread_pubkey_hex, KIT_FIXTURE.thread_secret_hex);

    const result = tryUnwrapMessage(
      {
        id: KIT_FIXTURE.wrap_id,
        pubkey: KIT_FIXTURE.wrap_pubkey,
        content: KIT_FIXTURE.wrap_content,
        tags: [['t', '70']],
      },
      store,
    );

    expect(result).not.toBeNull();
    expect(result!.plaintext).toBe(KIT_FIXTURE.plaintext);
    expect(result!.authorHex).toBe(KIT_FIXTURE.author_pubkey_hex);
    expect(result!.threadId).toBe(KIT_FIXTURE.thread_pubkey_hex);
  });

  it('wrong thread key cannot open the kit-made wrap', () => {
    const store = new ThreadKeyStore();
    const wrongSk = generateSecretKey();
    store.set(getPublicKey(wrongSk), wrongSk);

    const result = tryUnwrapMessage(
      {
        id: KIT_FIXTURE.wrap_id,
        pubkey: KIT_FIXTURE.wrap_pubkey,
        content: KIT_FIXTURE.wrap_content,
        tags: [['t', '70']],
      },
      store,
    );

    expect(result).toBeNull();
  });
});

describe('cross-implementation: tag format', () => {
  it('wrap has exactly [t, bucket] and [expiration, value] tags', () => {
    const threadSk = generateSecretKey();
    const now = 1727222400 + 43200;
    const wrap = wrapThreadMessage(
      'test', getPublicKey(generateSecretKey()), bytesToHex(threadSk), now,
    );

    expect(wrap.tags).toHaveLength(2);
    expect(wrap.tags[0][0]).toBe('t');
    expect(wrap.tags[0][1]).toMatch(/^[0-9a-f]{2}$/);
    expect(wrap.tags[1][0]).toBe('expiration');

    const wid = getWindowId(now);
    expect(wrap.tags[1][1]).toBe(String((wid + 2) * WINDOW_SECONDS));
  });
});
